#define DEBUG_DELAY_ENABLED
#define DEBUG_PRINT_DELAY_MS 1
#define DEBUG_YIELD_LOOP_DELAY_MS 25

// #define DISABLE_DEBUG_LAYER_HAL
// #define DISABLE_DEBUG_LAYER_DRIVERS
// #define DISABLE_DEBUG_LAYER_SERVICES
// #define DISABLE_DEBUG_LAYER_APP
// #define DISABLE_DEBUG_LAYER_SIM
