#ifndef TIMER_H
#define TIMER_H
#include <stdint.h>

typedef enum {
    TIMER0_MODE_NORMAL,
    TIMER0_MODE_CTC,
    TIMER0_MODE_PWM_FIXED_A,
    TIMER0_MODE_PWM_FIXED_B,
    TIMER0_MODE_PWM_FIXED_AB,
    TIMER0_MODE_PWM_VARIABLE_A,
    TIMER0_MODE_PWM_VARIABLE_B,
    TIMER0_MODE_PWM_VARIABLE_AB,
} timer0_mode_t;

typedef enum {
    TIMER0_CLOCK_OFF,
    TIMER0_CLOCK_1,
    TIMER0_CLOCK_8,
    TIMER0_CLOCK_64,
    TIMER0_CLOCK_256,
    TIMER0_CLOCK_1024,

    NUM_TIMER0_CLOCKS,
} timer0_clock_t;


typedef enum {
    TIMER0_PWM_CHANNEL_NONE,
    TIMER0_PWM_CHANNEL_A,
    TIMER0_PWM_CHANNEL_B,
    
    NUM_TIMER0_PWM_CHANNELS,
} timer0_pwm_channels


#endif